HW2, Unpack string package
Fuchsoria/go_hw pull request #2
Opened 2021-03-13 21:05 UTC by Fuchsoria

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-03-15 06:07 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/101901/9787/

Здравствуйте!
Хорошая работа, но, кажется, можно попроще.

Отписал в комментариях

2021-03-15 06:07 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +func validateRunes(i int, r rune, nextRune rune, inOneRune rune) (bool, error) {
92 по всему коду - magic number

2021-03-15 06:07 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +		if len(str)-1 >= i+currentRuneSize {
может вам работать не со следующей руной, а с предыдущей? и убрать всю эту логику

например, на очередном шаге проверяем:
- если руна до этого была цифрой - то делаем то-то
- если руна до этого была буквой - ...
- если руно до этого была `/`

и тд

т.е. достаточно набора флагов и хранения последней руны, текущая у вас есть всегда

код должен стать проще

2021-03-15 08:39 UTC, Fuchsoria commented on hw02_unpack_string/unpack.go
> +		if len(str)-1 >= i+currentRuneSize {
@Antonboom Как в таком случае можно определить была ли предыдущая руна экранированной цифрой или обычной? Изначально пробовал отталкиваться от предыдущего результата, но были затруднения из-за которых приходилось при 0 удалять последний символ в строке

2021-03-15 13:04 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +		if len(str)-1 >= i+currentRuneSize {
> Как в таком случае можно определить была ли предыдущая руна экранированной цифрой или обычной?

вы же знаете, в каком вы режиме сейчас находитесь (экранирования или нет), не понимаю проблемы

2021-03-15 13:08 UTC, Fuchsoria commented on hw02_unpack_string/unpack.go
> +		if len(str)-1 >= i+currentRuneSize {
Получается просто оставлять флаг о том была ли экранированна руна и на следующей итерации его учесть?

2021-03-15 13:40 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +		if len(str)-1 >= i+currentRuneSize {
как вариант, да

2021-03-16 04:19 UTC, Antonboom requested changes
Уже лучше!

Не кажется ли вам, что ветки местами дублируют друг друга и можно сократить их количество?

2021-03-16 12:02 UTC, Fuchsoria commented
> Уже лучше!
> 
> Не кажется ли вам, что ветки местами дублируют друг друга и можно сократить их количество?

@Antonboom Да есть такое ощущение, но количество веток связано с тем что старался покрыть максимальное количество специфичных случаев

2021-03-16 22:06 UTC, Fuchsoria commented
@Antonboom Уменьшил количество веток, провёл маленький рефакторинг

2021-03-17 04:15 UTC, Antonboom approved these changes
Принято
10 / 10

2021-03-19 16:34 UTC, merged