Add basic realisation of parallel execution
Fuchsoria/go_hw pull request #5
Opened 2021-04-10 23:36 UTC by Fuchsoria

## Домашнее задание №5 «Параллельное исполнение»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-04-12 05:36 UTC, kulti requested changes
Герман, хорошее начло. Интересное решение с закрытием канала внутри `once.Do()`.

Для зачета нужно будет добавить хотя бы один новый тест. Без новых тестов максимум будет 6 баллов.

Решение пока не совсем корректное. Написал вопросы, над которыми можно подумать, чтобы поправить. Также есть несколько предложений по улучшению кода. Если будут вопросы можете писать в личку в слаке.

2021-04-12 05:36 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +	t.Run("hundred workers without errors", func(t *testing.T) {
Это не новые тесты. Это те же самые, что уже есть, но с другим количеством воркеров и задач. Новые тесты должны тестировать что-то новое, что еще не протестировано другими тестами.

2021-04-12 05:36 UTC, kulti commented on hw05_parallel_execution/run.go
> +	limit := make(chan bool)
Зачем передавать bool в канал, если это значение никак не используется? Раз значение не нужно, можно сделать `chan struct{}`.

2021-04-12 05:36 UTC, kulti commented on hw05_parallel_execution/run.go
> +					errors <- true
Из этого канала же никто не читает. Довольно странно выглядит.

Для счетчика можно использовать atomic (будут рассказывать на второй части занятия про примитивы синхронизации).

2021-04-12 05:36 UTC, kulti commented on hw05_parallel_execution/run.go
> +	ch := make(chan Task, len(tasks))
Зачем этому каналу буфер?

2021-04-12 05:36 UTC, kulti commented on hw05_parallel_execution/run.go
> +	wg.Wait()
Это ожидание того, что все таски были обработаны, но по условию обработка задач должна прекратиться, если количество ошибок превысит m.

Код делает вид, что работает как надо, но по факту воркеры продолжает разбирать таски, просто игнорируют.

Предлагаю подумать над таким вопросом — какую задачу вы пытались решить на самом деле с помощью этой wg и killsignal? Что на самом деле нужно ждать?

2021-04-14 19:07 UTC, Fuchsoria commented on hw05_parallel_execution/run.go
> +					errors <- true
Изменил

2021-04-14 19:07 UTC, Fuchsoria commented on hw05_parallel_execution/run.go
> +	limit := make(chan bool)
Изменил

2021-04-19 21:31 UTC, Fuchsoria commented on hw05_parallel_execution/run.go
> +	wg.Wait()
Изменено

2021-04-19 21:32 UTC, Fuchsoria commented on hw05_parallel_execution/run.go
> +	ch := make(chan Task, len(tasks))
Буфер убран

2021-04-19 21:33 UTC, Fuchsoria commented on hw05_parallel_execution/run_test.go
> +	t.Run("hundred workers without errors", func(t *testing.T) {
Добавил тест микс контента (таски с ошибками и без одновременно, рандомная генерация), тест тасков с возможными nil value вместо таска

2021-04-20 06:07 UTC, kulti approved these changes
После обсуждения в слаке решение стало коротким и понятным.

К тестам пока еще есть вопросы. Придумался интересный случай для nil-тасок 👍 Другой тест ничего нового не добавляет. Если хотите побольше баллов за тесты, то подумайте еще над использованием Run — что в него можно передавать, а что нельзя.

Пока принято с 7/10 (1 за чистоту, 2 за тесты).

2021-04-20 06:07 UTC, kulti commented on hw05_parallel_execution/run.go
>  	return nil
А почему просто не `return err`?

2021-04-20 06:07 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +			rand.Seed(time.Now().UnixNano())
А какой смысл выставлять Seed каждый раз перед вызовом rand.Intn?

Вообще, вручную выставлять Seed не нужно, он примерно также выставляется автоматически. Вручную полезно выставлять, если его писать в логи, чтобы потом повторить цепочку сгенерированных значений.

2021-04-20 06:07 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +				atomic.AddInt64(&totalNilTasks, 1)
Зачем тут атомик?

2021-04-20 06:07 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		require.Equal(t, doneTasks+totalNilTasks, int64(maxTasks), "total tasks + nils should be equal to max tasks")
Не сразу понял, что это за проверка.

Думаю, логичнее выглядело бы что-то вроде: `require.Equal(t, nonNilTasks, doneTasks)`. Т.е. посчитать не-nil таски при создании слайса тасок и убедиться, что именно столько и выполнилось.

Может показаться, что обе проверки об одном и том же, но они говорят разное. Текущая говорит, что сумма двух каунтеров равна другому числу. И это выглядит супер очевидно, т.к. именно так слайс тасок и собирался. Нужно делать выводы, рассуждать. Предложенный мною вариант сразу проверяет то, что выполнилось только нужное кол-во тасок.

2021-04-20 06:07 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		if totalErrorTasks >= int64(maxErrorsCount) {
Не самый лучший подход к созданию тестов. Тут получилось, что внутри теста два теста и либо один выполниться, либо другой. Это означает, что надо написать два теста.

По сути в этот тест собраны уже написанные тесты. Мы пишем тесты не ради тестов, а ради проверки сценариев.

2021-04-20 20:34 UTC, Fuchsoria commented on hw05_parallel_execution/run_test.go
> +		if totalErrorTasks >= int64(maxErrorsCount) {
Убрал миксовый тест, добавил тесты для проверки сломанных аргументов, 0 и негативных значений воркеров и макс ошибок, пустой слайс либо nil вместо слайса, добавил 2 новых типа ошибки и вывод их

2021-04-20 20:34 UTC, Fuchsoria commented on hw05_parallel_execution/run_test.go
> +		require.Equal(t, doneTasks+totalNilTasks, int64(maxTasks), "total tasks + nils should be equal to max tasks")
Да так выходит логичнее, изменил

2021-04-20 20:34 UTC, Fuchsoria commented on hw05_parallel_execution/run_test.go
> +			rand.Seed(time.Now().UnixNano())
Убрал

2021-04-20 20:34 UTC, Fuchsoria commented on hw05_parallel_execution/run_test.go
> +				atomic.AddInt64(&totalNilTasks, 1)
Убрано

2021-04-20 20:35 UTC, Fuchsoria commented on hw05_parallel_execution/run.go
>  	return nil
Изменил

2021-04-23 05:54 UTC, kulti commented on hw05_parallel_execution/run.go
> +		return err
Опять же, почему не просто `return ErrNoWorkers`? :)

2021-04-23 05:54 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +			rand.Seed(time.Now().UnixNano())
> Вообще, вручную выставлять Seed не нужно, он примерно также выставляется автоматически.
В этом я ошибся. Автоматически Seed ставится всегда в 1. Если хочется получить разные данные на каждый запуск, то можно в начале каждого теста добавить. Либо добавить main_test.go, где завести функцию TestMain, в которой уже один раз выставить Seed на все тесты.

2021-04-23 05:58 UTC, kulti approved these changes
Работа над кодом произведена на 4+. Осталась одна шерховатость, но я не понимаю, почему вы такой многословный код пишите. Тут, видимо, вам нужно поанализировать, порефлексировать, чтобы в будущем лучше получалось.

Тесты добавлены 👍 

Поднимаю баллы до 10.

2021-04-26 18:07 UTC, Fuchsoria commented on hw05_parallel_execution/run.go
> +		return err
Изменил

2021-04-26 18:10 UTC, merged