HW06 Pipeline
Fuchsoria/go_hw pull request #6
Opened 2021-05-03 20:48 UTC by Fuchsoria

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-05-08 16:35 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/101901/9801/

Есть вопросики.

2021-05-08 16:35 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +		for item := range in {
здесь вы можете заблокироваться, если во входной канал никто не будет писать, но при этом придёт done

2021-05-08 16:35 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +			<-done
для чего это?

2021-05-08 17:31 UTC, Fuchsoria commented on hw06_pipeline_execution/pipeline.go
> +			<-done
В начала была проверка с for select, пропустил что done бесполезен

2021-05-08 17:32 UTC, Fuchsoria commented on hw06_pipeline_execution/pipeline.go
> +		for item := range in {
> здесь вы можете заблокироваться, если во входной канал никто не будет писать, но при этом придёт done

Воссоздать такой случай не получилось, добавил немного простых тестов на проверку входных/выходных данных

2021-05-08 19:14 UTC, Antonboom requested changes

2021-05-08 19:14 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +			return
Как у вас прошли тесты? Вы здесь выходите и код ниже не выполняется.
Спуллил себе проект - у меня done-кейс упал.

2021-05-08 19:14 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +		for item := range in {
такой случай воссоздаёт тест "done and empty channel"

или реализуйте свой тест, в котором вы создаёте пайплайн и ничего не давая на вход, закрываете done

сейчас, видимо, это работает из-за return выше. т.е. вы соединили 1 стейдж и вышли, тест обманут, но пайплайн работает неверно.

но поэтому иногда падает тест с done посередине

2021-05-13 16:29 UTC, Fuchsoria commented on hw06_pipeline_execution/pipeline.go
> +			return
Тест не упал при прогоне х100

2021-05-17 11:24 UTC, Antonboom approved these changes
Обсудили лично.

Супер!
Принято
10 / 10

2021-05-17 16:31 UTC, merged