Hw09 struct validator
Fuchsoria/go_hw pull request #9
Opened 2021-05-22 19:57 UTC by Fuchsoria

## Домашнее задание №9 «Валидатор структур»

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-05-25 17:22 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/101901/9792/

Здравствуйте!
Спасибо за работу.

Готов принять после смены сигнатуры функции назад.

2021-05-25 17:22 UTC, Antonboom commented on hw09_struct_validator/validator.go
> +	errStrs := make([]string, 0)
strings.Builder?

2021-05-25 17:22 UTC, Antonboom commented on hw09_struct_validator/validator.go
> +		return nil, ErrExpectedStruct
а какой тип получили?

2021-05-25 17:22 UTC, Antonboom commented on hw09_struct_validator/validator.go
> +		checkValue(&errs, field.Name, validateTag, fv)
этой функции бы возвращать слайс подобно `append`

изменять слайсы через указатель - не go way

2021-05-25 17:22 UTC, Antonboom commented on hw09_struct_validator/validator.go
> +func Validate(v interface{}) (ValidationErrors, error) {
читаем ТЗ:
```
Необходимо реализовать функцию
func Validate(v interface{}) error
```

2021-05-25 17:33 UTC, Fuchsoria commented on hw09_struct_validator/validator.go
> +func Validate(v interface{}) (ValidationErrors, error) {
В таком случае получается что тестировать придётся общую ошибку? А это как я понимаю уже будет проверка по строке, либо что-то не понимаю

2021-05-25 17:35 UTC, Fuchsoria commented on hw09_struct_validator/validator.go
> +		return nil, ErrExpectedStruct
Любой кроме структуры

2021-05-25 17:50 UTC, Antonboom commented on hw09_struct_validator/validator.go
> +		return nil, ErrExpectedStruct
я к тому, что как понять из ошибки, что за тип?

2021-05-25 17:50 UTC, Antonboom commented on hw09_struct_validator/validator.go
> +func Validate(v interface{}) (ValidationErrors, error) {
пакет `errors` в помощь

2021-05-26 20:03 UTC, Fuchsoria commented on hw09_struct_validator/validator.go
> +	errStrs := make([]string, 0)
Изменил на билдер

2021-05-26 20:03 UTC, Fuchsoria commented on hw09_struct_validator/validator.go
> +		return nil, ErrExpectedStruct
Добавил информацию в ошибку

2021-05-26 20:03 UTC, Fuchsoria commented on hw09_struct_validator/validator.go
> +		checkValue(&errs, field.Name, validateTag, fv)
Изменил

2021-05-26 20:04 UTC, Fuchsoria commented on hw09_struct_validator/validator.go
> +func Validate(v interface{}) (ValidationErrors, error) {
Изменил

2021-05-27 04:14 UTC, Antonboom approved these changes
Супер!

Принято
10 / 10

2021-05-27 07:07 UTC, merged